services:
  users-api:
    build: .
    container_name: users-api
    ports:
      - "8000:8000"
    environment:
      DATABASE_URL: postgresql://postgres:postgres123@postgres-db:5432/user_db
    depends_on:
      - postgres-db
    restart: always

  postgres-db:
    image: postgres:16
    container_name: postgres-db
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres123
      POSTGRES_DB: user_db
    ports:
      - "5432:5432"